export const defaultSkin = {
  skin: "default",
  bodyBg: '#f1f8fa',
  bodyTextColor: '#111',
  headerBg: 'rgba(255 255 255 / 20%)',
  headerTextColor: '#111',
  calculatorTextColor: '#242e41',
  borderColor: 'rgba(36 46 65 / 7%)',
  fontSize: '1rem',
  fontSizeSm: '.75rem',
  fontSizeLg: '1.75rem',
  animationTime: '0.2s',
  animationType: 'ease-out',
  gap: '0.25rem',
  borderRadius: '0.25rem',
  borderRadiusLg: '0.5rem',
};

export const minimalSkin = {
  skin: "minimal",
  bodyBg: '#fff',
  bodyTextColor: '#111',
  headerBg: 'rgba(255 255 255 / 20%)',
  headerTextColor: '#111',
  calculatorTextColor: '#111',
  borderColor: 'rgba(#242e41, 0.07)',
  fontSize: '1rem',
  fontSizeSm: '.875rem',
  fontSizeLg: '2rem',
  animationTime: '0.15s',
  animationType: 'ease-out',
  gap: '1rem',
  borderRadius: '0.25rem',
  borderRadiusLg: '1.5rem',
};

export const retroSkin = {
  skin: "retro",
  bodyBg: '#333',
  bodyTextColor: '#fff',
  headerBg: 'rgba(0 0 0 / 10%)',
  headerTextColor: '#fff',
  calculatorTextColor: '#fff',
  borderColor: 'rgba(#242e41, 0.07)',
  fontSize: '1rem',
  fontSizeSm: '.75rem',
  fontSizeLg: '2rem',
  animationTime: '0s',
  animationType: 'ease-out',
  gap: '0.5rem',
  borderRadius: '0.25rem',
  borderRadiusLg: '0.5rem',
};
